-- MySQL Script generated by MySQL Workbench
-- Fri Mar 29 12:25:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Models` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Brands_id` INT NOT NULL,
  `year` YEAR(4) NOT NULL,
  `car_mileage` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Models_Brands_idx` (`Brands_id` ASC) VISIBLE,
  CONSTRAINT `fk_Models_Brands`
    FOREIGN KEY (`Brands_id`)
    REFERENCES `mydb`.`Brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `VIN` CHAR(17) NOT NULL,
  `Models_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `VIN_UNIQUE` (`VIN` ASC) VISIBLE,
  INDEX `fk_Cars_Models1_idx` (`Models_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Models1`
    FOREIGN KEY (`Models_id`)
    REFERENCES `mydb`.`Models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `contact_info` TEXT(4000) NOT NULL,
  `Cars_id` INT NOT NULL,
  `driver_license` VARCHAR(50) NOT NULL,
  `phone_number` CHAR(20) NOT NULL,
  ` comments` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Clients_Cars1_idx` (`Cars_id` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Cars1`
    FOREIGN KEY (`Cars_id`)
    REFERENCES `mydb`.`Cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NOT NULL,
  `Clients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Schedule_Clients1_idx` (`Clients_id` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_Clients1`
    FOREIGN KEY (`Clients_id`)
    REFERENCES `mydb`.`Clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RepairOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RepairOrders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('new', 'process', 'cancelled', 'completed') NOT NULL DEFAULT 'new',
  `Cars_id` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `Schedule_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RepairOrders_Cars1_idx` (`Cars_id` ASC) VISIBLE,
  INDEX `fk_RepairOrders_Schedule1_idx` (`Schedule_id` ASC) VISIBLE,
  CONSTRAINT `fk_RepairOrders_Cars1`
    FOREIGN KEY (`Cars_id`)
    REFERENCES `mydb`.`Cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RepairOrders_Schedule1`
    FOREIGN KEY (`Schedule_id`)
    REFERENCES `mydb`.`Schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RepairOrders_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `quantity` SMALLINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_Parts_RepairOrders1_idx` (`RepairOrders_id` ASC) VISIBLE,
  CONSTRAINT `fk_Parts_RepairOrders1`
    FOREIGN KEY (`RepairOrders_id`)
    REFERENCES `mydb`.`RepairOrders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `position` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RepairOrders_has_Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RepairOrders_has_Staff` (
  `RepairOrders_id` INT NOT NULL,
  `Staff_id` INT NOT NULL,
  PRIMARY KEY (`RepairOrders_id`, `Staff_id`),
  INDEX `fk_RepairOrders_has_Staff_Staff1_idx` (`Staff_id` ASC) VISIBLE,
  INDEX `fk_RepairOrders_has_Staff_RepairOrders1_idx` (`RepairOrders_id` ASC) VISIBLE,
  CONSTRAINT `fk_RepairOrders_has_Staff_RepairOrders1`
    FOREIGN KEY (`RepairOrders_id`)
    REFERENCES `mydb`.`RepairOrders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RepairOrders_has_Staff_Staff1`
    FOREIGN KEY (`Staff_id`)
    REFERENCES `mydb`.`Staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `status` ENUM('paid', 'unpaid') NOT NULL DEFAULT 'unpaid',
  `RepairOrders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_RepairOrders1_idx` (`RepairOrders_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_RepairOrders1`
    FOREIGN KEY (`RepairOrders_id`)
    REFERENCES `mydb`.`RepairOrders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
